services:
  # Db service - PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: gopher-postgres
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_secret
      POSTGRES_DB: gopher_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  #  Cache service - Redis
  redis:
    image: redis:7-alpine
    container_name: gopher-redis
    ports:
      - "6379:6379"

  #  Object storage service - MinIO
  minio:
    image: minio/minio
    container_name: gopher-minio
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console UI
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  #  Message broker service - RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: connectvn_rabbitmq
    ports:
      - "5672:5672"   # Cổng cho code Golang gọi vào
      - "15672:15672" # Cổng giao diện Web để cậu xem tin nhắn
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  pgdata:
  minio_data: